ignore:
  - "**/*g.dart"
  - "**/*gr.dart"
  - "**/*freezed.dart"
  
coverage:
  status:
    project:
      default:
        target: 90%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target